"""Change Types year

Revision ID: 8ac20eac3f32
Revises: cf11896ae731
Create Date: 2025-03-13 11:36:27.236289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ac20eac3f32'
down_revision: Union[str, None] = 'cf11896ae731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
