"""change type

Revision ID: b4c1d773d79d
Revises: cf1e63191f62
Create Date: 2025-03-12 14:41:41.879508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c1d773d79d'
down_revision: Union[str, None] = 'cf1e63191f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartments', 'parking',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('apartments', 'elevator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('elevator', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('apartments', 'parking',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
