"""Initial migration

Revision ID: cf1e63191f62
Revises: 
Create Date: 2025-03-11 17:52:48.608102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1e63191f62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('location', sa.String(), nullable=False),
        sa.Column('price', sa.Float(), nullable=False),
        sa.Column('price_meters', sa.Float(), nullable=False),
        sa.Column('new', sa.Boolean(), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('room', sa.Integer(), nullable=False),
        sa.Column('area', sa.Float(), nullable=False),
        sa.Column('floor', sa.Integer(), nullable=False),
        sa.Column('type', sa.Integer(), nullable=False),
        sa.Column('parking', sa.Boolean(), nullable=False),
        sa.Column('repair', sa.Integer(), nullable=False),
        sa.Column('balcony', sa.Boolean(), nullable=False),
        sa.Column('elevator', sa.Boolean(), nullable=False),
        sa.Column('district', sa.String(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments')
    # ### end Alembic commands ###
