services:
  db:
    image: postgres:17
    container_name: apart_db
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data


  document:
    image: apart_image
    build:
      context: .
    container_name: apart_app
    env_file:
      - .env
    depends_on:
      - db
    command: ['/apart_analyser/docker/app.sh']
    ports:
      - "127.0.0.1:8000:8000"

networks:  
  default:  
    driver: bridge  
    driver_opts:  
      com.docker.network.driver.mtu: 1450

volumes:
  fastapi_postgres_data: